atoms:
  stack.Stack.elts: [elts, Stack.elts]
  stack.Stack.length: [length, Stack.length]
axioms: {}
binders: {}
binops: {}
datatypes: {}
defs: {}
name: Why3.stack.Stack
prefix_ops: {}
types:
  stack.Stack.t: [t, Stack.t]
