From Coq Require Import Strings.String.
From Coq Require Import String Ascii.
From Coq Require Arith.
From stdpp Require Import base.
From stdpp Require Import fin_maps.
From stdpp Require Import gmap.
From stdpp Require Import base gmultiset.
From Coq Require Classical.
From Coq Require Import ZArith.
From stdpp.bitvector Require Import definitions tactics.
From Coq Require Import Sorting.Sorted.
From Coq Require Import Reals.Rbasic_fun.
From Coq Require Import Reals.Abstract.ConstructiveAbs.
From Coq Require Import Reals.Rdefinitions.
From stdpp Require Import list_relations.
From stdpp Require Import list_numbers.
From stdpp Require Import functions.
From Coq Require Import ClassicalEpsilon.
From stdpp Require Import base decidable.
From Coq Require Import ZArith.Zeuclid.
From Coq Require Import ZArith.Znumtheory.
From stdpp Require Import propset.
From Coq Require Import Reals.
Require Import Why3.Base.
Require Import Why3.real.Sum.
Require Import Why3.ieee_float.RoundingMode.
Require Import Why3.ufloat.USingle.
Require Import Why3.ufloat.HelperLemmas.
Open Scope Z_scope.
Axiom uadd_single_error_propagation : forall  (x_f : usingle) (x : R) (x_rel : R) (x_factor : R) (x_abs : R) (y_f : usingle) (y : R) (y_rel : R) (y_factor : R) (y_abs : R) (r : usingle) (fact0 : Rle (Rabs (Rminus (to_real x_f) x)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real y_f) y)) (Rplus (Rmult y_rel y_factor) y_abs)) (fact2 : Rle (Rabs x) x_factor) (fact3 : Rle (Rabs y) y_factor) (fact4 : Rle 0%R x_rel) (fact5 : Rle 0%R y_rel) (fact6 : Rle 0%R x_abs) (fact7 : Rle 0%R y_abs) (fact8 : r = uadd x_f y_f), Rle (Rabs (Rminus (to_real r) (Rplus x y))) (Rplus (Rmult (Rplus (Rplus x_rel y_rel) eps) (Rplus x_factor y_factor)) (Rplus (Rmult (Rplus (Rplus 1%R eps) y_rel) x_abs) (Rmult (Rplus (Rplus 1%R eps) x_rel) y_abs))).
Axiom usub_single_error_propagation : forall  (x_f : usingle) (x : R) (x_rel : R) (x_factor : R) (x_abs : R) (y_f : usingle) (y : R) (y_rel : R) (y_factor : R) (y_abs : R) (r : usingle) (fact0 : Rle (Rabs (Rminus (to_real x_f) x)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real y_f) y)) (Rplus (Rmult y_rel y_factor) y_abs)) (fact2 : Rle (Rabs x) x_factor) (fact3 : Rle (Rabs y) y_factor) (fact4 : Rle 0%R x_abs) (fact5 : Rle 0%R y_abs) (fact6 : Rle 0%R x_rel) (fact7 : Rle 0%R y_rel) (fact8 : r = usub x_f y_f), Rle (Rabs (Rminus (to_real r) (Rminus x y))) (Rplus (Rmult (Rplus (Rplus x_rel y_rel) eps) (Rplus x_factor y_factor)) (Rplus (Rmult (Rplus (Rplus 1%R eps) y_rel) x_abs) (Rmult (Rplus (Rplus 1%R eps) x_rel) y_abs))).
Axiom umul_single_error_propagation : forall  (x_f : usingle) (x : R) (x_rel : R) (x_factor : R) (x_abs : R) (y_f : usingle) (y : R) (y_rel : R) (y_factor : R) (y_abs : R) (r : usingle) (fact0 : Rle (Rabs (Rminus (to_real x_f) x)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real y_f) y)) (Rplus (Rmult y_rel y_factor) y_abs)) (fact2 : Rle (Rabs x) x_factor) (fact3 : Rle (Rabs y) y_factor) (fact4 : Rle 0%R x_rel) (fact5 : Rle 0%R y_rel) (fact6 : Rle 0%R x_abs) (fact7 : Rle 0%R y_abs) (fact8 : r = umul x_f y_f), Rle (Rabs (Rminus (to_real r) (Rmult x y))) (Rplus (Rmult (Rplus eps (Rmult (Rplus (Rplus x_rel y_rel) (Rmult x_rel y_rel)) (Rplus 1%R eps))) (Rmult x_factor y_factor)) (Rplus (Rmult (Rplus (Rplus (Rmult (Rplus y_abs (Rmult y_abs x_rel)) x_factor) (Rmult (Rplus x_abs (Rmult x_abs y_rel)) y_factor)) (Rmult x_abs y_abs)) (Rplus 1%R eps)) eta)).
Axiom log_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (logx_f : usingle) (log_rel : R) (log_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real logx_f) (ln (to_real x_f)))) (Rplus (Rmult log_rel (Rabs (ln (to_real x_f)))) log_abs)) (fact2 : Rlt 0%R x_exact) (fact3 : Rle x_exact x_factor) (fact4 : Rlt 0%R (Rminus (Rminus x_exact (Rmult x_rel x_factor)) x_abs)) (fact5 : Rle 0%R log_rel), Rle (Rabs (Rminus (to_real logx_f) (ln x_exact))) (Rplus (Rmult log_rel (Rabs (ln x_exact))) (Rplus (Rmult (Ropp (ln (Rminus 1%R (Rdiv (Rplus (Rmult x_rel x_factor) x_abs) x_exact)))) (Rplus 1%R log_rel)) log_abs)).
Axiom log2_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (log2x_f : usingle) (log_rel : R) (log_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real log2x_f) (Rlog 2 (to_real x_f)))) (Rplus (Rmult log_rel (Rabs (Rlog 2 (to_real x_f)))) log_abs)) (fact2 : Rlt 0%R x_exact) (fact3 : Rle x_exact x_factor) (fact4 : Rlt 0%R (Rminus (Rminus x_exact (Rmult x_rel x_factor)) x_abs)) (fact5 : Rle 0%R log_rel), Rle (Rabs (Rminus (to_real log2x_f) (Rlog 2 x_exact))) (Rplus (Rmult log_rel (Rabs (Rlog 2 x_exact))) (Rplus (Rmult (Ropp (Rlog 2 (Rminus 1%R (Rdiv (Rplus (Rmult x_rel x_factor) x_abs) x_exact)))) (Rplus 1%R log_rel)) log_abs)).
Axiom log10_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (log10x_f : usingle) (log_rel : R) (log_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real log10x_f) (Rlog 10 (to_real x_f)))) (Rplus (Rmult log_rel (Rabs (Rlog 10 (to_real x_f)))) log_abs)) (fact2 : Rlt 0%R x_exact) (fact3 : Rle x_exact x_factor) (fact4 : Rlt 0%R (Rminus (Rminus x_exact (Rmult x_rel x_factor)) x_abs)) (fact5 : Rle 0%R log_rel), Rle (Rabs (Rminus (to_real log10x_f) (Rlog 10 x_exact))) (Rplus (Rmult log_rel (Rabs (Rlog 10 x_exact))) (Rplus (Rmult (Ropp (Rlog 10 (Rminus 1%R (Rdiv (Rplus (Rmult x_rel x_factor) x_abs) x_exact)))) (Rplus 1%R log_rel)) log_abs)).
Axiom exp_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (expx_f : usingle) (exp_rel : R) (exp_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real expx_f) (exp (to_real x_f)))) (Rplus (Rmult exp_rel (exp (to_real x_f))) exp_abs)) (fact2 : Rle x_exact x_factor) (fact3 : Rle 0%R exp_rel) (fact4 : Rle exp_rel 1%R), Rle (Rabs (Rminus (to_real expx_f) (exp x_exact))) (Rplus (Rmult (Rplus exp_rel (Rmult (Rminus (exp (Rplus (Rmult x_rel x_factor) x_abs)) 1%R) (Rplus 1%R exp_rel))) (exp x_exact)) exp_abs).
Axiom sin_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (sinx_f : usingle) (sin_rel : R) (sin_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real sinx_f) (sin (to_real x_f)))) (Rplus (Rmult sin_rel (Rabs (sin (to_real x_f)))) sin_abs)) (fact2 : Rle x_exact x_factor) (fact3 : Rle 0%R sin_rel), Rle (Rabs (Rminus (to_real sinx_f) (sin x_exact))) (Rplus (Rmult sin_rel (Rabs (sin x_exact))) (Rplus (Rmult (Rplus (Rmult x_rel x_factor) x_abs) (Rplus 1%R sin_rel)) sin_abs)).
Axiom cos_single_error_propagation : forall  (x_f : usingle) (x_exact : R) (x_rel : R) (x_factor : R) (x_abs : R) (cosx_f : usingle) (cos_rel : R) (cos_abs : R) (fact0 : Rle (Rabs (Rminus (to_real x_f) x_exact)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs (Rminus (to_real cosx_f) (cos (to_real x_f)))) (Rplus (Rmult cos_rel (Rabs (cos (to_real x_f)))) cos_abs)) (fact2 : Rle x_exact x_factor) (fact3 : Rle 0%R cos_rel), Rle (Rabs (Rminus (to_real cosx_f) (cos x_exact))) (Rplus (Rmult cos_rel (Rabs (cos x_exact))) (Rplus (Rmult (Rplus (Rmult x_rel x_factor) x_abs) (Rplus 1%R cos_rel)) cos_abs)).
Axiom real_fun : (Z -> usingle) -> Z -> R.
Axiom real_fun'def : forall  (f : Z -> usingle) (i : Z), real_fun f i = to_real (f i).
Axiom sum_single_error_propagation : forall  (n : Z) (f : Z -> usingle) (f_exact : Z -> R) (f_rel : R) (f_factor : Z -> R) (f_abs : R) (f_factor' : Z -> R) (x : usingle) (sum_rel : R) (sum_abs : R) (fact0 : ∀(i : Z), 0%Z ≤ i ∧ i < n -> Rle (Rabs (Rminus (real_fun f i) (f_exact i))) (Rplus (Rmult f_rel (f_factor i)) f_abs)) (fact1 : ∀(i : Z), 0%Z ≤ i ∧ i < n -> Rle (Rminus (Rminus (f_factor i) (Rmult f_rel (f_factor i))) f_abs) (f_factor' i) ∧ Rle (f_factor' i) (Rplus (Rplus (f_factor i) (Rmult f_rel (f_factor i))) f_abs)) (fact2 : Rle (Rabs (Rminus (to_real x) (sum (real_fun f) 0%Z n))) (Rplus (Rmult sum_rel (sum f_factor' 0%Z n)) sum_abs)) (fact3 : Rle 0%R sum_rel) (fact4 : 0%Z ≤ n), Rle (Rabs (Rminus (to_real x) (sum f_exact 0%Z n))) (Rplus (Rmult (Rplus f_rel (Rmult sum_rel (Rplus 1%R f_rel))) (sum f_factor 0%Z n)) (Rplus (Rmult (Rmult f_abs (Rdefinitions.IZR n)) (Rplus 1%R sum_rel)) sum_abs)).
Axiom udiv_closure : usingle -> usingle -> usingle.
Axiom udiv_exact_single_error_propagation : forall  (x_f : usingle) (x : R) (x_rel : R) (x_factor : R) (x_abs : R) (y_f : usingle) (r : usingle) (fact0 : Rle (Rabs (Rminus (to_real x_f) x)) (Rplus (Rmult x_rel x_factor) x_abs)) (fact1 : Rle (Rabs x) x_factor) (fact2 : Rle 0%R x_rel) (fact3 : Rle 0%R x_abs) (fact4 : ¬ 0%R = to_real y_f) (fact5 : is_exact udiv_closure x_f y_f) (fact6 : r = infix_slslsldot x_f y_f), Rle (Rabs (Rminus (to_real r) (Rdiv x (to_real y_f)))) (Rplus (Rmult x_rel (Rdiv x_factor (Rabs (to_real y_f)))) (Rplus (Rdiv x_abs (Rabs (to_real y_f))) eta)).
