import Why3.Base
import Why3.real.Sum
import Why3.ieee_float.RoundingMode
import Why3.ufloat.UDouble
import Why3.ufloat.HelperLemmas
open Classical
open Lean4Why3
namespace UDoubleLemmas
axiom uadd_double_error_propagation (x_f : UDouble.udouble) (x : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (y_f : UDouble.udouble) (y : ℝ) (y_rel : ℝ) (y_factor : ℝ) (y_abs : ℝ) (r : UDouble.udouble) (fact0 : abs (UDouble.to_real x_f - x) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real y_f - y) ≤ y_rel * y_factor + y_abs) (fact2 : abs x ≤ x_factor) (fact3 : abs y ≤ y_factor) (fact4 : (0 : ℝ) ≤ x_rel) (fact5 : (0 : ℝ) ≤ y_rel) (fact6 : (0 : ℝ) ≤ x_abs) (fact7 : (0 : ℝ) ≤ y_abs) (fact8 : r = UDouble.uadd x_f y_f) : abs (UDouble.to_real r - (x + y)) ≤ (x_rel + y_rel + UDouble.eps) * (x_factor + y_factor) + (((1 : ℝ) + UDouble.eps + y_rel) * x_abs + ((1 : ℝ) + UDouble.eps + x_rel) * y_abs)
axiom usub_double_error_propagation (x_f : UDouble.udouble) (x : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (y_f : UDouble.udouble) (y : ℝ) (y_rel : ℝ) (y_factor : ℝ) (y_abs : ℝ) (r : UDouble.udouble) (fact0 : abs (UDouble.to_real x_f - x) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real y_f - y) ≤ y_rel * y_factor + y_abs) (fact2 : abs x ≤ x_factor) (fact3 : abs y ≤ y_factor) (fact4 : (0 : ℝ) ≤ x_abs) (fact5 : (0 : ℝ) ≤ y_abs) (fact6 : (0 : ℝ) ≤ x_rel) (fact7 : (0 : ℝ) ≤ y_rel) (fact8 : r = UDouble.usub x_f y_f) : abs (UDouble.to_real r - (x - y)) ≤ (x_rel + y_rel + UDouble.eps) * (x_factor + y_factor) + (((1 : ℝ) + UDouble.eps + y_rel) * x_abs + ((1 : ℝ) + UDouble.eps + x_rel) * y_abs)
axiom umul_double_error_propagation (x_f : UDouble.udouble) (x : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (y_f : UDouble.udouble) (y : ℝ) (y_rel : ℝ) (y_factor : ℝ) (y_abs : ℝ) (r : UDouble.udouble) (fact0 : abs (UDouble.to_real x_f - x) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real y_f - y) ≤ y_rel * y_factor + y_abs) (fact2 : abs x ≤ x_factor) (fact3 : abs y ≤ y_factor) (fact4 : (0 : ℝ) ≤ x_rel) (fact5 : (0 : ℝ) ≤ y_rel) (fact6 : (0 : ℝ) ≤ x_abs) (fact7 : (0 : ℝ) ≤ y_abs) (fact8 : r = UDouble.umul x_f y_f) : abs (UDouble.to_real r - x * y) ≤ (UDouble.eps + (x_rel + y_rel + x_rel * y_rel) * ((1 : ℝ) + UDouble.eps)) * (x_factor * y_factor) + (((y_abs + y_abs * x_rel) * x_factor + (x_abs + x_abs * y_rel) * y_factor + x_abs * y_abs) * ((1 : ℝ) + UDouble.eps) + UDouble.eta)
axiom log_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (logx_f : UDouble.udouble) (log_rel : ℝ) (log_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real logx_f - Real.log (UDouble.to_real x_f)) ≤ log_rel * abs (Real.log (UDouble.to_real x_f)) + log_abs) (fact2 : (0 : ℝ) < x_exact) (fact3 : x_exact ≤ x_factor) (fact4 : (0 : ℝ) < x_exact - x_rel * x_factor - x_abs) (fact5 : (0 : ℝ) ≤ log_rel) : abs (UDouble.to_real logx_f - Real.log x_exact) ≤ log_rel * abs (Real.log x_exact) + (-Real.log ((1 : ℝ) - (x_rel * x_factor + x_abs) / x_exact) * ((1 : ℝ) + log_rel) + log_abs)
axiom log2_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (log2x_f : UDouble.udouble) (log_rel : ℝ) (log_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real log2x_f - Real.logb 2 (UDouble.to_real x_f)) ≤ log_rel * abs (Real.logb 2 (UDouble.to_real x_f)) + log_abs) (fact2 : (0 : ℝ) < x_exact) (fact3 : x_exact ≤ x_factor) (fact4 : (0 : ℝ) < x_exact - x_rel * x_factor - x_abs) (fact5 : (0 : ℝ) ≤ log_rel) : abs (UDouble.to_real log2x_f - Real.logb 2 x_exact) ≤ log_rel * abs (Real.logb 2 x_exact) + (-Real.logb 2 ((1 : ℝ) - (x_rel * x_factor + x_abs) / x_exact) * ((1 : ℝ) + log_rel) + log_abs)
axiom log10_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (log10x_f : UDouble.udouble) (log_rel : ℝ) (log_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real log10x_f - Real.logb 10 (UDouble.to_real x_f)) ≤ log_rel * abs (Real.logb 10 (UDouble.to_real x_f)) + log_abs) (fact2 : (0 : ℝ) < x_exact) (fact3 : x_exact ≤ x_factor) (fact4 : (0 : ℝ) < x_exact - x_rel * x_factor - x_abs) (fact5 : (0 : ℝ) ≤ log_rel) : abs (UDouble.to_real log10x_f - Real.logb 10 x_exact) ≤ log_rel * abs (Real.logb 10 x_exact) + (-Real.logb 10 ((1 : ℝ) - (x_rel * x_factor + x_abs) / x_exact) * ((1 : ℝ) + log_rel) + log_abs)
axiom exp_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (expx_f : UDouble.udouble) (exp_rel : ℝ) (exp_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real expx_f - Real.exp (UDouble.to_real x_f)) ≤ exp_rel * Real.exp (UDouble.to_real x_f) + exp_abs) (fact2 : x_exact ≤ x_factor) (fact3 : (0 : ℝ) ≤ exp_rel) (fact4 : exp_rel ≤ (1 : ℝ)) : abs (UDouble.to_real expx_f - Real.exp x_exact) ≤ (exp_rel + (Real.exp (x_rel * x_factor + x_abs) - (1 : ℝ)) * ((1 : ℝ) + exp_rel)) * Real.exp x_exact + exp_abs
axiom sin_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (sinx_f : UDouble.udouble) (sin_rel : ℝ) (sin_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real sinx_f - Real.sin (UDouble.to_real x_f)) ≤ sin_rel * abs (Real.sin (UDouble.to_real x_f)) + sin_abs) (fact2 : x_exact ≤ x_factor) (fact3 : (0 : ℝ) ≤ sin_rel) : abs (UDouble.to_real sinx_f - Real.sin x_exact) ≤ sin_rel * abs (Real.sin x_exact) + ((x_rel * x_factor + x_abs) * ((1 : ℝ) + sin_rel) + sin_abs)
axiom cos_double_error_propagation (x_f : UDouble.udouble) (x_exact : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (cosx_f : UDouble.udouble) (cos_rel : ℝ) (cos_abs : ℝ) (fact0 : abs (UDouble.to_real x_f - x_exact) ≤ x_rel * x_factor + x_abs) (fact1 : abs (UDouble.to_real cosx_f - Real.cos (UDouble.to_real x_f)) ≤ cos_rel * abs (Real.cos (UDouble.to_real x_f)) + cos_abs) (fact2 : x_exact ≤ x_factor) (fact3 : (0 : ℝ) ≤ cos_rel) : abs (UDouble.to_real cosx_f - Real.cos x_exact) ≤ cos_rel * abs (Real.cos x_exact) + ((x_rel * x_factor + x_abs) * ((1 : ℝ) + cos_rel) + cos_abs)
axiom real_fun : (ℤ -> UDouble.udouble) -> ℤ -> ℝ
axiom real_fun'def (f : ℤ -> UDouble.udouble) (i : ℤ) : real_fun f i = UDouble.to_real (f i)
axiom sum_double_error_propagation (n : ℤ) (f : ℤ -> UDouble.udouble) (f_exact : ℤ -> ℝ) (f_rel : ℝ) (f_factor : ℤ -> ℝ) (f_abs : ℝ) (f_factor' : ℤ -> ℝ) (x : UDouble.udouble) (sum_rel : ℝ) (sum_abs : ℝ) (fact0 : ∀(i : ℤ), (0 : ℤ) ≤ i ∧ i < n → abs (real_fun f i - f_exact i) ≤ f_rel * f_factor i + f_abs) (fact1 : ∀(i : ℤ), (0 : ℤ) ≤ i ∧ i < n → f_factor i - f_rel * f_factor i - f_abs ≤ f_factor' i ∧ f_factor' i ≤ f_factor i + f_rel * f_factor i + f_abs) (fact2 : abs (UDouble.to_real x - real.Sum.sum (real_fun f) (0 : ℤ) n) ≤ sum_rel * real.Sum.sum f_factor' (0 : ℤ) n + sum_abs) (fact3 : (0 : ℝ) ≤ sum_rel) (fact4 : (0 : ℤ) ≤ n) : abs (UDouble.to_real x - real.Sum.sum f_exact (0 : ℤ) n) ≤ (f_rel + sum_rel * ((1 : ℝ) + f_rel)) * real.Sum.sum f_factor (0 : ℤ) n + (f_abs * Int.to_Real n * ((1 : ℝ) + sum_rel) + sum_abs)
axiom udiv_closure : UDouble.udouble -> UDouble.udouble -> UDouble.udouble
axiom udiv_exact_single_error_propagation (x_f : UDouble.udouble) (x : ℝ) (x_rel : ℝ) (x_factor : ℝ) (x_abs : ℝ) (y_f : UDouble.udouble) (r : UDouble.udouble) (fact0 : abs (UDouble.to_real x_f - x) ≤ x_rel * x_factor + x_abs) (fact1 : abs x ≤ x_factor) (fact2 : (0 : ℝ) ≤ x_rel) (fact3 : (0 : ℝ) ≤ x_abs) (fact4 : ¬(0 : ℝ) = UDouble.to_real y_f) (fact5 : UDouble.is_exact udiv_closure x_f y_f) (fact6 : r = UDouble.infix_slslsldot x_f y_f) : abs (UDouble.to_real r - x / UDouble.to_real y_f) ≤ x_rel * (x_factor / abs (UDouble.to_real y_f)) + (x_abs / abs (UDouble.to_real y_f) + UDouble.eta)
end UDoubleLemmas
