theory c_StrlenLemmas
  imports "NTP4Verif.NTP4Verif" "Why3STD.Ref_Ref" c_C int_Unsigned c_String
begin
axiomatization where strlen_before_null:   "\<not>of_char (s (ofs + i)) = (0 :: int)"
 if "(0 :: int) \<le> i"
 and "i < strlen s ofs"
  for i :: "int"
  and s :: "int \<Rightarrow> char"
  and ofs :: "int"
axiomatization where strlen_at_null:   "of_char (s (ofs + strlen s ofs)) = (0 :: int)"
 if "(0 :: int) \<le> strlen s ofs"
  for s :: "int \<Rightarrow> char"
  and ofs :: "int"
axiomatization where strlen_not_0:   "i < strlen s ofs"
 if "(0 :: int) \<le> i"
 and "i < strlen s ofs"
 and "\<not>of_char (s (ofs + i)) = (0 :: int)"
  for i :: "int"
  and s :: "int \<Rightarrow> char"
  and ofs :: "int"
axiomatization where strlen_0:   "i = strlen s ofs"
 if "(0 :: int) \<le> i"
 and "i < strlen s ofs"
 and "of_char (s (ofs + i)) = (0 :: int)"
  for i :: "int"
  and s :: "int \<Rightarrow> char"
  and ofs :: "int"
axiomatization where strlen_sup'0:   "(0 :: int) \<le> strlen s ofs"
 if "(0 :: int) \<le> i"
 and "of_char (s (ofs + i)) = (0 :: int)"
  for i :: "int"
  and s :: "int \<Rightarrow> char"
  and ofs :: "int"
axiomatization where strlen_sup'1:   "strlen s ofs \<le> i"
 if "(0 :: int) \<le> i"
 and "of_char (s (ofs + i)) = (0 :: int)"
  for i :: "int"
  and s :: "int \<Rightarrow> char"
  and ofs :: "int"
end
